// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSiAPVlTvytlFKd7ao-eDNCuy_Cx8TbOw',
    appId: '1:860882029296:web:cbf7ff897675d7f998d035',
    messagingSenderId: '860882029296',
    projectId: 'cross-platform-57b89',
    authDomain: 'cross-platform-57b89.firebaseapp.com',
    storageBucket: 'cross-platform-57b89.firebasestorage.app',
    measurementId: 'G-KT7GH5JBZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGLGuJakCI8Xk_ZmFp01TKGikhBOmgcWw',
    appId: '1:860882029296:android:b4c484bb6cb100df98d035',
    messagingSenderId: '860882029296',
    projectId: 'cross-platform-57b89',
    storageBucket: 'cross-platform-57b89.firebasestorage.app',
  );
}
